# Site settings
name: XiaomiFirmwareUpdater
title: Xiaomi Firmware Updater
description: ""
baseurl: ""
author: berkantkz
repository: XiaomiFirmwareUpdater/xiaomifirmwareupdater.github.io

# Build settings
markdown: kramdown
permalinks: pretty
exclude:
    - xfu-node/node_modules
    
members:
    - berkantkz
    - yshalsager